task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-13-1
      image_family: freebsd-12-3

  pkginstall_script:
    - pkg install -y autoconf automake libtool bash git gcc
    - ln -s /usr/local/bin/bash /bin/

  compile_script:
    - ./build_and_test.sh clean
 
